plugins { id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" }
ext.minecraft_version = '1.21.9'
ext.minecraft_dependency = '1.21.9'
ext.impl_version = '1.0.7'
ext.java_version = 21
ext.modmenu_version = '16.0.1'
ext.legacy_mappings = true
ext.client_source_dirs = ['src/common/java', 'src/legacybase/java', 'src/iconbuttonrl/java', 'src/legacy129/java', 'src/legacy1216/java']
apply from: rootProject.file('gradle/version.gradle')
